import flamengo from "../../assets/times/flamengo.png";
import palmeiras from "../../assets/times/palmeiras.png";
import saoPaulo from "../../assets/times/saopaulo.png";
import corinthians from "../../assets/times/corinthians.png";
import gremio from "../../assets/times/gremio.png";
import internacional from "../../assets/times/internacional.png";
import atletico from "../../assets/times/atleticomg.png";
import cruzeiro from "../../assets/times/cruzeiro.png";
import fluminense from "../../assets/times/fluminense.png";
import botafogo from "../../assets/times/botafogo.png";
import vasco from "../../assets/times/vasco.png";
import bahia from "../../assets/times/bahia.png";

export const partidasMockadas = [
  {
    id: 1,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Flamengo", imagem: flamengo, gols: 2 },
    timeB: { nome: "Palmeiras", imagem: palmeiras, gols: 1 },
    dia: 1,
  },
  {
    id: 2,
    campeonato: "Paulistão",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "São Paulo", imagem: saoPaulo, gols: 1 },
    timeB: { nome: "Corinthians", imagem: corinthians, gols: 0 },
    dia: 2,
  },
  {
    id: 3,
    campeonato: "Gaúcho",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Grêmio", imagem: gremio, gols: 2 },
    timeB: { nome: "Internacional", imagem: internacional, gols: 2 },
    dia: 3,
  },
  {
    id: 4,
    campeonato: "Mineiro",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Atlético-MG", imagem: atletico, gols: 3 },
    timeB: { nome: "Cruzeiro", imagem: cruzeiro, gols: 1 },
    dia: 4,
  },
  {
    id: 5,
    campeonato: "Carioca",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Fluminense", imagem: fluminense, gols: 2 },
    timeB: { nome: "Botafogo", imagem: botafogo, gols: 2 },
    dia: 5,
  },
  {
    id: 6,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Vasco", imagem: vasco, gols: 1 },
    timeB: { nome: "Bahia", imagem: bahia, gols: 0 },
    dia: 6,
  },
  {
    id: 7,
    campeonato: "Copa do Brasil",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Flamengo", imagem: flamengo, gols: 4 },
    timeB: { nome: "São Paulo", imagem: saoPaulo, gols: 3 },
    dia: 7,
  },
  {
    id: 8,
    campeonato: "Libertadores",
    horario: "11:00",
    status: "ENCERRADO",
    timeA: { nome: "Palmeiras", imagem: palmeiras, gols: 3 },
    timeB: { nome: "Corinthians", imagem: corinthians, gols: 1 },
    dia: 8,
  },
  {
    id: 9,
    campeonato: "Brasileirão",
    horario: "13:00",
    status: "AGORA",
    timeA: { nome: "Atlético-MG", imagem: atletico, gols: 2 },
    timeB: { nome: "Grêmio", imagem: gremio, gols: 0 },
    dia: 8,
  },
  {
    id: 10,
    campeonato: "Carioca",
    horario: "16:00",
    status: "EM BREVE",
    timeA: { nome: "Vasco", imagem: vasco, gols: "-" },
    timeB: { nome: "Fluminense", imagem: fluminense, gols: "-" },
    dia: 8,
  },
  {
    id: 11,
    campeonato: "Brasileirão",
    horario: "14:00",
    status: "AGORA",
    timeA: { nome: "Internacional", imagem: internacional, gols: 1 },
    timeB: { nome: "Cruzeiro", imagem: cruzeiro, gols: 1 },
    dia: 8,
  },
  {
    id: 12,
    campeonato: "Copa do Brasil",
    horario: "17:30",
    status: "EM BREVE",
    timeA: { nome: "Bahia", imagem: bahia, gols: "-" },
    timeB: { nome: "Flamengo", imagem: flamengo, gols: "-" },
    dia: 8,
  },
  {
    id: 14,
    campeonato: "Brasileirão",
    horario: "18:00",
    status: "EM BREVE",
    timeA: { nome: "São Paulo", imagem: saoPaulo, gols: "-" },
    timeB: { nome: "Internacional", imagem: internacional, gols: "-" },
    dia: 8,
  },
  {
    id: 15,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Corinthians", imagem: corinthians, gols: "-" },
    timeB: { nome: "Fluminense", imagem: fluminense, gols: "-" },
    dia: 9,
  },
  {
    id: 16,
    campeonato: "Copa do Brasil",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Cruzeiro", imagem: cruzeiro, gols: "-" },
    timeB: { nome: "Vasco", imagem: vasco, gols: "-" },
    dia: 9,
  },
  {
    id: 17,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Bahia", imagem: bahia, gols: "-" },
    timeB: { nome: "Grêmio", imagem: gremio, gols: "-" },
    dia: 9,
  },
  {
    id: 18,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Internacional", imagem: internacional, gols: "-" },
    timeB: { nome: "Botafogo", imagem: botafogo, gols: "-" },
    dia: 10,
  },
  {
    id: 19,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Flamengo", imagem: flamengo, gols: "-" },
    timeB: { nome: "Corinthians", imagem: corinthians, gols: "-" },
    dia: 10,
  },
  {
    id: 20,
    campeonato: "Libertadores",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Palmeiras", imagem: palmeiras, gols: "-" },
    timeB: { nome: "Grêmio", imagem: gremio, gols: "-" },
    dia: 11,
  },
  {
    id: 21,
    campeonato: "Copa do Brasil",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "São Paulo", imagem: saoPaulo, gols: "-" },
    timeB: { nome: "Cruzeiro", imagem: cruzeiro, gols: "-" },
    dia: 12,
  },
  {
    id: 22,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Atlético-MG", imagem: atletico, gols: "-" },
    timeB: { nome: "Internacional", imagem: internacional, gols: "-" },
    dia: 13,
  },
  {
    id: 23,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Vasco", imagem: vasco, gols: "-" },
    timeB: { nome: "Palmeiras", imagem: palmeiras, gols: "-" },
    dia: 14,
  },
  {
    id: 24,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Fluminense", imagem: fluminense, gols: "-" },
    timeB: { nome: "Bahia", imagem: bahia, gols: "-" },
    dia: 15,
  },
  {
    id: 25,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Botafogo", imagem: botafogo, gols: "-" },
    timeB: { nome: "Atlético-MG", imagem: atletico, gols: "-" },
    dia: 16,
  },
  {
    id: 26,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Corinthians", imagem: corinthians, gols: "-" },
    timeB: { nome: "Grêmio", imagem: gremio, gols: "-" },
    dia: 17,
  },
  {
    id: 27,
    campeonato: "Copa do Brasil",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Cruzeiro", imagem: cruzeiro, gols: "-" },
    timeB: { nome: "Flamengo", imagem: flamengo, gols: "-" },
    dia: 18,
  },
  {
    id: 28,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Bahia", imagem: bahia, gols: "-" },
    timeB: { nome: "Internacional", imagem: internacional, gols: "-" },
    dia: 19,
  },
  {
    id: 29,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Grêmio", imagem: gremio, gols: "-" },
    timeB: { nome: "Vasco", imagem: vasco, gols: "-" },
    dia: 20,
  },
  {
    id: 30,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "São Paulo", imagem: saoPaulo, gols: "-" },
    timeB: { nome: "Fluminense", imagem: fluminense, gols: "-" },
    dia: 21,
  },
  {
    id: 31,
    campeonato: "Copa do Brasil",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Palmeiras", imagem: palmeiras, gols: "-" },
    timeB: { nome: "Cruzeiro", imagem: cruzeiro, gols: "-" },
    dia: 22,
  },
  {
    id: 32,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Flamengo", imagem: flamengo, gols: "-" },
    timeB: { nome: "Atlético-MG", imagem: atletico, gols: "-" },
    dia: 23,
  },
  {
    id: 33,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Corinthians", imagem: corinthians, gols: "-" },
    timeB: { nome: "Bahia", imagem: bahia, gols: "-" },
    dia: 24,
  },
  {
    id: 34,
    campeonato: "Libertadores",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Grêmio", imagem: gremio, gols: "-" },
    timeB: { nome: "Flamengo", imagem: flamengo, gols: "-" },
    dia: 25,
  },
  {
    id: 35,
    campeonato: "Carioca",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Vasco", imagem: vasco, gols: "-" },
    timeB: { nome: "Botafogo", imagem: botafogo, gols: "-" },
    dia: 26,
  },
  {
    id: 36,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Internacional", imagem: internacional, gols: "-" },
    timeB: { nome: "São Paulo", imagem: saoPaulo, gols: "-" },
    dia: 27,
  },
  {
    id: 37,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Fluminense", imagem: fluminense, gols: "-" },
    timeB: { nome: "Palmeiras", imagem: palmeiras, gols: "-" },
    dia: 28,
  },
  {
    id: 38,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Atlético-MG", imagem: atletico, gols: "-" },
    timeB: { nome: "Corinthians", imagem: corinthians, gols: "-" },
    dia: 29,
  },
  {
    id: 39,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Cruzeiro", imagem: cruzeiro, gols: "-" },
    timeB: { nome: "Grêmio", imagem: gremio, gols: "-" },
    dia: 30,
  },
  {
    id: 40,
    campeonato: "Libertadores",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Palmeiras", imagem: palmeiras, gols: "-" },
    timeB: { nome: "Flamengo", imagem: flamengo, gols: "-" },
    dia: 31,
  },
  {
    id: 41,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "São Paulo", imagem: saoPaulo, gols: 3 },
    timeB: { nome: "Vasco", imagem: vasco, gols: 0 },
    dia: 1,
  },
  {
    id: 42,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Internacional", imagem: internacional, gols: 2 },
    timeB: { nome: "Fluminense", imagem: fluminense, gols: 2 },
    dia: 2,
  },
  {
    id: 43,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Atlético-MG", imagem: atletico, gols: 4 },
    timeB: { nome: "Bahia", imagem: bahia, gols: 1 },
    dia: 3,
  },
  {
    id: 44,
    campeonato: "Copa do Brasil",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Cruzeiro", imagem: cruzeiro, gols: 0 },
    timeB: { nome: "Botafogo", imagem: botafogo, gols: 0 },
    dia: 4,
  },
  {
    id: 45,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Palmeiras", imagem: palmeiras, gols: 2 },
    timeB: { nome: "Corinthians", imagem: corinthians, gols: 1 },
    dia: 5,
  },
  {
    id: 46,
    campeonato: "Copa do Brasil",
    horario: "19:30",
    status: "ENCERRADO",
    timeA: { nome: "Flamengo", imagem: flamengo, gols: 4 },
    timeB: { nome: "São Paulo", imagem: saoPaulo, gols: 2 },
    dia: 6,
  },
  {
    id: 47,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Vasco", imagem: vasco, gols: "-" },
    timeB: { nome: "Atlético-MG", imagem: atletico, gols: "-" },
    dia: 10,
  },
  {
    id: 48,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Fluminense", imagem: fluminense, gols: "-" },
    timeB: { nome: "Cruzeiro", imagem: cruzeiro, gols: "-" },
    dia: 11,
  },
  {
    id: 49,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Botafogo", imagem: botafogo, gols: "-" },
    timeB: { nome: "Internacional", imagem: internacional, gols: "-" },
    dia: 12,
  },
  {
    id: 50,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Bahia", imagem: bahia, gols: "-" },
    timeB: { nome: "Flamengo", imagem: flamengo, gols: "-" },
    dia: 13,
  },
  {
    id: 51,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Corinthians", imagem: corinthians, gols: "-" },
    timeB: { nome: "Grêmio", imagem: gremio, gols: "-" },
    dia: 14,
  },
  {
    id: 52,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Atlético-MG", imagem: atletico, gols: "-" },
    timeB: { nome: "Fluminense", imagem: fluminense, gols: "-" },
    dia: 15,
  },
  {
    id: 53,
    campeonato: "Copa do Brasil",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Cruzeiro", imagem: cruzeiro, gols: "-" },
    timeB: { nome: "Palmeiras", imagem: palmeiras, gols: "-" },
    dia: 16,
  },
  {
    id: 54,
    campeonato: "Paulistão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "São Paulo", imagem: saoPaulo, gols: "-" },
    timeB: { nome: "Corinthians", imagem: corinthians, gols: "-" },
    dia: 17,
  },
  {
    id: 55,
    campeonato: "Carioca",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Flamengo", imagem: flamengo, gols: "-" },
    timeB: { nome: "Vasco", imagem: vasco, gols: "-" },
    dia: 18,
  },
  {
    id: 56,
    campeonato: "Gaúcho",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Grêmio", imagem: gremio, gols: "-" },
    timeB: { nome: "Internacional", imagem: internacional, gols: "-" },
    dia: 19,
  },
  {
    id: 57,
    campeonato: "Mineiro",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Atlético-MG", imagem: atletico, gols: "-" },
    timeB: { nome: "Cruzeiro", imagem: cruzeiro, gols: "-" },
    dia: 20,
  },
  {
    id: 58,
    campeonato: "Libertadores",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Palmeiras", imagem: palmeiras, gols: "-" },
    timeB: { nome: "Grêmio", imagem: gremio, gols: "-" },
    dia: 21,
  },
  {
    id: 59,
    campeonato: "Copa do Brasil",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "São Paulo", imagem: saoPaulo, gols: "-" },
    timeB: { nome: "Cruzeiro", imagem: cruzeiro, gols: "-" },
    dia: 22,
  },
  {
    id: 60,
    campeonato: "Brasileirão",
    horario: "19:30",
    status: "EM BREVE",
    timeA: { nome: "Flamengo", imagem: flamengo, gols: "-" },
    timeB: { nome: "Atlético-MG", imagem: atletico, gols: "-" },
    dia: 23,
  },
];
